services:
  database:
    image: postgres:14.2-alpine3.15
    container_name: studx_pg
    restart: unless-stopped
    volumes:
      - ./container/pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${STUDX_DB_NAME:-studx}
      POSTGRES_PASSWORD: ${STUDX_DB_PASSWD:-studx}
      POSTGRES_USER: ${STUDX_DB_USER:-studx}
  redis:
    image: redis:7.0-alpine3.16
    container_name: studx_redis
    restart: unless-stopped
  # Application services
  writepad:
    build: ./writepad/
    ports:
      - "9090:9090"
  whiteboard:
    image: rofl256/whiteboard:latest
    ports:
      - "8080:8080"
  rooms:
    build: ./rooms
    env_file:
      - .env
    environment:
      - STUDX_REDIS_URL=redis://redis:6379
      - STUDX_ROOMS_ADDRESS=0.0.0.0:5000
    depends_on:
      - database
  api:
    image: studx-api
    build: ./api
    depends_on:
      - database
    volumes:
      - media:/opt/app/media
    env_file:
      - .env
    environment:
      - PORT=6000
      - STUDX_REDIS_URL=redis://redis:6379
      - STUDX_DB_HOST=database
  # Proxy
  caddy:
    build: ./ui
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - media:/api/media
      - $PWD/Caddyfile.prod:/etc/caddy/Caddyfile
      # - caddy_data:/data
      # - caddy_config:/config

volumes:
  media:
#   caddy_data:
#     external: true
#   caddy_config:
