services:
  # Essential services
  database:
    image: postgres:14.2-alpine3.15
    container_name: studx_pg
    restart: unless-stopped
    command: [ "postgres", "-c", "log_statement=all" ]
    env_file:
      - .env
    ports:
      - ${STUDX_DB_PORT:-5432}:5432
    volumes:
      - ./container/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${STUDX_DB_NAME:-studx}
      POSTGRES_PASSWORD: ${STUDX_DB_PASSWD:-studx}
      POSTGRES_USER: ${STUDX_DB_USER:-studx}
  redis:
    image: redis:7.0-alpine3.16
    container_name: studx_redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${STUDX_REDIS_PORT:-6380}:6379
  # Application services
  writepad-hocuspocus:
    build: ./writepad/
    ports:
      - "9090:9090"
  whiteboard:
    image: rofl256/whiteboard:latest
    ports:
      - "8080:8080"
  api:
    build: ./api
    env_file:
      - .env
