# Generated by Django 4.1.4 on 2023-01-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studx", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
