# Generated by Django 4.1.4 on 2023-01-21 22:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studx", "0002_alter_organization_name_alter_organization_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organizationmembership",
            unique_together={("org", "user")},
        ),
    ]
