version: "3.9"

services:
  database:
    image: postgres:14.2-alpine3.15
    container_name: studx_pg
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - ${POSTGRES_DB_PORT:-5432}:5432
    volumes:
      - ./container/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-studx}
      POSTGRES_PASSWORD: ${DB_PASSWD:-studx}
      POSTGRES_USER: ${DB_USER:-studx}

  redis:
    image: redis:7.0-alpine3.16
    container_name: studx_redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379

